# Generated by Django 2.2.14 on 2020-07-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_text', models.CharField(max_length=200)),
                ('update_datetime', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
    ]
