version: '3'
services:
    db:
      image: mysql:5.7
      container_name: db
      restart: always
      environment:
        MYSQL_HOST: 'localhost'
        MYSQL_PORT: '3306'
        MYSQL_DATABASE: 'my_db'
        MYSQL_USER: 'mgnl'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - "3306:3306"
    frontend:
        build: ./frontend
        command: ["npm", "start"]
        volumes: 
            - ./frontend:/app/frontend
            - /app/frontend/node_modules
        ports:
            - "3001:3000"
    web:
      build: ./api
      restart: always
      command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
      volumes:
        - ./api:/app/api
      ports:
        - "8002:8000"
      depends_on:
        - db